### ISSUE TITLE
Publicity

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/blockchain-commons-patron-agreement#2]
@christophera, what rules will BC and its clients/patrons follow about mentioning each other publicly?  When and how can BC use the names and logos of its patrons, and vice versa?

**Comment by ChristopherA** [comment]
Standard language in a few different agreements: 

> Publicity. Both parties agree to generally coordinate upon the public release of information about the general subject matter of this Agreement when mutually beneficial. Notwithstanding such future public release, after the Effective Date, either party may refer publicly state that Consultant is acting as a consultant and advisor for Company.

Note that at one point it was clear that a company actually just wanted to list my name as an advisor for an ICO, and I decided not to sign the agreement once I realized it. Not sure what I would have done if I'd signed it.

-- Christopher Allen

**Comment by kemitchell** [comment]
Thanks.
