### ISSUE TITLE
Counterparty Responsiveness

### ISSUE THREAD

**Issue by kemitchell** [kemitchell/blockchain-commons-patron-agreement#3]
@christophera, I can put a section to the effect of "the company will make its people respond to questions in a reasonable time", but other than as a gotcha to point back to, that won't actually do much for you. We should put in some thought about what the contract says BC should be able to _do_ when the other side isn't responsive.

The obvious one is postponing deadlines.  If you slide past a deadline because you couldn't get word back from the other side, that's not your fault.  It shouldn't affect your pay or billing.

The other obvious point is an out from the contract.  If you have repeated trouble getting word out of a counterparty, to the point where you don't want to keep going with them, you should be able to terminate the contract.

Perhaps you could share a few anecdotes of unresponsive clients?  That could be raw material for more ideas about legal "remedies" the contract can provided when the other side won't get back to you.

**Comment by ChristopherA** [comment]
SICPA: We didn't have in the contract regular meetings. We found that they had difficulty in scheduling, in particular during summer months, both from a business event perspective and European-style vacations. Feedback was extremely slow and we'd go sometimes weeks without knowing if we were offering what they wanted (we were not). If there was feedback, it was only in the infrequent meetings. In the end, after six months they got something that they found useful, but it was not quite what they wanted, and they found were not able to commit to utilize the work we were creating, so they cancelled the retainer (which was a minimum 6 months.

HTC: It worked best when we had weekly meetings where they would detail their questions in advance, I would respond with initial answers via email, then we'd have a discussion via Zoom. Some weeks they'd only have 1 question. Sometimes they ran out of questions for a few weeks, in particular near holidays or crunch time deliverables dates. There were also times when I was traveling in different time zones or attending a specific event during the regular time and needed different schedule, sometimes we were able to reschedule, sometimes not. A key point for Blockchain Commons terminating the contract was that some point they needed expertise I could not personally offer, but knew people who could, but I was not under the contract allowed to bring others in to answer. This went on for over two months, and they did not terminate, so I did.

**Comment by kemitchell** [comment]
Takeaways so far:

- [x] Add a patron commitment to respond promptly to questions and scheduling requests.
- [x] Add a patron commitment to work with you on scheduling conflicts and rescheduling.
- [ ] Toll deadlines by the length of any patron-side delay.
- [ ] Fees continue to accumulate while work stands on hold due to patron delays.
- [ ] Blockchain Commons termination right for repeated delays.
